# Generated by Django 4.0.4 on 2022-07-08 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='cover',
        ),
    ]
