# Generated by Django 4.0.4 on 2022-07-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_remove_books_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='cover',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
